version: "3.8"

services:

  # PostgreSQL Database
  database:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_DB: fitness_demo
      POSTGRES_USER: root
      POSTGRES_PASSWORD: MyNewPass@123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Spring Boot App
  backend:
    build: .
    container_name: fitness_container
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://database:5432/fitness_demo
      DB_USER: root
      DB_PWD: MyNewPass@123
    depends_on:
      - database
    restart: unless-stopped

volumes:
  postgres_data: